title_name = "The Bigs 2"
title_id = "54540830" # TT-2083
hash = "5187638D00D4A75A" # default.xex
#media_id = "00000000"

[[patch]]
    name = "Enable Debug Menu"
    desc = "Required for Debug Settings and Cheats."
    author = "UndeadFrankie"
    is_enabled = false

    [[patch.be8]]
        address = 0x825D4C98
        value = 0x00

[[patch]]
    name = "Skip Intro Logos"
    desc = "Skips 2K and BCG logos."
    author = "UndeadFrankie"
    is_enabled = false

    [[patch.be16]]
        address = 0x822B8960
        value = 0x4800
		
